//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDownloader.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubLesson
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<int> LessonId { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
